### ISSUE TITLE
当执行make rucbase后报错

### ISSUE THREAD

**Issue by Soulter** [ruc-deke/rucbase-lab#1]
您好！感谢您推出这个出色的项目。
我们按照[使用文档](https://github.com/ruc-deke/rucbase-lab/blob/main/docs/Rucbase%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3.md)尝试将此项目部署在自己的机器上，但是好像出了一些问题。

```
mkdir build
cd build 
cmake .. [-DCMAKE_BUILD_TYPE=Debug]|[-DCMAKE_BUILD_TYPE=Release]
make rucbase <-j4>|<-j8> # 选择4 or 8线程编译，如果你不想选择，那么make -j也是可以的
```

尝试执行第四条指令时，报了如下错误：
```
make: *** No rule to make target 'rucbase'.  Stop.
```

请问如何解决呢，会不会是MakeFile文件不对导致的？

**Comment by Waldenth** [comment]
你好！因为这个项目是之前用来进行课程实践试用的，所以没有一开始就把所有的编译选项打开(因为没完成“lab”编译服务端时可能会出错)。如果你希望编译，可以去/src/CMakeLists.txt查看，里面注释掉了服务端的编译命令，取消注释即可。

**Comment by Soulter** [comment]
好的，谢谢！

**Comment by lzl-hello** [comment]
你好，我也遇到了这个问题，可是我打开/src/CMakeLists,txt中并没有看到注释掉的命令：
include_directories(${CMAKE_CURRENT_SOURCE_DIR})

add_subdirectory(analyze)
add_subdirectory(record)
add_subdirectory(index)
add_subdirectory(system)
add_subdirectory(execution)
add_subdirectory(parser)
add_subdirectory(optimizer)
add_subdirectory(storage)
add_subdirectory(common)
add_subdirectory(replacer)
add_subdirectory(transaction)
add_subdirectory(recovery)
add_subdirectory(test)


target_link_libraries(parser execution pthread)

add_executable(rmdb rmdb.cpp)
target_link_libraries(rmdb parser execution readline pthread planner analyze)

**Comment by neighthorn** [comment]
> 你好，我也遇到了这个问题，可是我打开/src/CMakeLists,txt中并没有看到注释掉的命令： include_directories(${CMAKE_CURRENT_SOURCE_DIR})
> 
> add_subdirectory(analyze) add_subdirectory(record) add_subdirectory(index) add_subdirectory(system) add_subdirectory(execution) add_subdirectory(parser) add_subdirectory(optimizer) add_subdirectory(storage) add_subdirectory(common) add_subdirectory(replacer) add_subdirectory(transaction) add_subdirectory(recovery) add_subdirectory(test)
> 
> target_link_libraries(parser execution pthread)
> 
> add_executable(rmdb rmdb.cpp) target_link_libraries(rmdb parser execution readline pthread planner analyze)

你好，我们更新了代码框架，在新版本的实验中，可运行的target为rmdb，需要执行make rmdb命令来进行编译

**Comment by neighthorn** [comment]
> 请问在未开始补全代码之前，服务器端 make rmdb 只能进行到31%，有error出现是正常现象吗？

如果是shared_ptr error，可以在transaction.h中添加#include<memory>头文件，这是由于框架在macOS进行开发，实际Ubuntu系统中需要添加memory头文件，现在已经修复了这个问题。
