### ISSUE TITLE
关于该实验的学习资源

### ISSUE THREAD

**Issue by bosswnx** [ruc-deke/rucbase-lab#2]
您好！感谢您推出这个出色的项目。
我们是今年打算参加计算机系统能力大赛数据库赛道的学生。比赛主页面的推荐了您的这个 lab 作为参考。鉴于现在距离比赛开始还有一定的时间，我们打算尝试完成这个 lab 来锻炼自己的能力。
但是我们发现 lab 没有提供可以参考的学习资料，我们做起来感觉十分吃力，想请教有没有什么适合的课程或教材来学习并辅助完成这个 lab 呢？

**Comment by QiYuZhuang** [comment]
docs/* 目录下有关于lab详细的文档。完成 lab 需要一些数据库实现的基础知识，课程推荐 CMU-15445以及配套练习，辅导书可以选择《Database System Concept》。

**Comment by bosswnx** [comment]
好的！非常感谢🥰
